### ISSUE TITLE
Multi-Calculator - Python 3.6

### ISSUE THREAD

**Issue by DefGamerGreg** [DefGamerGreg/Multi-Calculator#2]
Multi-Calculator with Python 3
https://github.com/DefGamerGreg/Multi-Calculator.git

I made a multi calculator for learning the concept of programs
Help needed for improvement 
I want to make this calculator more advance and could calculate more than just basic math
I am looking forward for advice 

I will continue to work on this code to make it better, simpler, and advance
I’m pretty new to Python programming 
So helps and attentions are highly needed it

Thanks!
(Read more at Pull request on my homepage)

**Comment by GemedetAdept** [comment]
Hello! I'm going to start working on this by implementing algebraic expressions and tidying the code, as listed in the push request.

**Comment by DefGamerGreg** [comment]
I’m also going to put you to the project, work on it when ever you are free, I’m still learning take it slow. Thank u for joining me here.

**Comment by GemedetAdept** [comment]
> I’m also going to put you to the project, work on it when ever you are free, I’m still learning take it slow. Thank u for joining me here.

Sounds good! I'm in the same boat as you are, so don't worry. I've dabbled with programming since high school, but I only started seriously practicing it this past year. Likewise, I'm not an expert by _any_ means, but I'd be more than happy to help you out with learning Python! It's my favorite language by far, and I'm a sucker for some good PEP8, Pythonic code.

I'll try to keep up with this project when I can, but it'll likely be a bit scattered, as my freelance work takes up a considerable amount of my time.

And hey, thank _you_ for letting me join in and help out with this project! I'm still pretty new to GitHub, and I'm pretty anxious (in both senses of the word) to be working on projects and helping out!

– Vivian Z.
